using KriptoCore.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace deneme_web.Dtos
{
    public class CategoryDto
    {
        public BTC BTC { get; set; }
        public ETH ETH { get; set; }
        public XRP XRP { get; set; }
        public BCH BCH { get; set; }
        public LTC LTC { get; set; }
        public USDT USDT { get; set; }
        public EOS EOS { get; set; }
        public ADA ADA { get; set; }
        public XMR XMR { get; set; }
        public OMG OMG { get; set; }
        public MIOTA MIOTA { get; set; }
        public WAVES WAVES { get; set; }
        public PPT PPT { get; set; }
        public XLM XLM { get; set; }
        public REQ REQ { get; set; }
        public HSR HSR { get; set; }
        public IOST IOST { get; set; }
        public CND CND { get; set; }
        public VIBE VIBE { get; set; }
        public LUN LUN { get; set; }
        public VIB VIB { get; set; }
        public CMT CMT { get; set; }
        public ICX ICX { get; set; }
        public ETC ETC { get; set; }
        public NEO NEO { get; set; }
        public DSH DSH { get; set; }
        public VEN VEN { get; set; }
        public TRX TRX { get; set; }
        public POE POE { get; set; }
        public MANA MANA { get; set; }
        public MTH MTH { get; set; }
        public ELF ELF { get; set; }
        public STRAT STRAT { get; set; }
        public XZC XZC { get; set; }
        public WTC WTC { get; set; }
        public ENJ ENJ { get; set; }
        public ZRX ZRX { get; set; }
        public ZEC ZEC { get; set; }
        public ZEN ZEN { get; set; }
        public ZIL ZIL { get; set; }
        public AE AE { get; set; }
        public ALGO ALGO { get; set; }
        public ARDR ARDR { get; set; }
        public ARK ARK { get; set; }
        public BAT BAT { get; set; }
        public REP REP { get; set; }
        public AOA AOA { get; set; }
        public BNB BNB { get; set; }
        public BSV BSV { get; set; }
        public BCD BCD { get; set; }
        public BTG BTG { get; set; }
        public BTS BTS { get; set; }
        public BTT BTT { get; set; }
        public BTMX BTMX { get; set; }
        public BCN BCN { get; set; }
        public BTM BTM { get; set; }
        public XLINK XLINK { get; set; }
        public CRO CRO { get; set; }
        public DAI DAI { get; set; }
        public DCR DCR { get; set; }
        public DENT DENT { get; set; }
        public DGB DGB { get; set; }
        public XMX XMX { get; set; }
        public WAXP WAXP { get; set; }
        public ATOM ATOM { get; set; }
        public DOGE DOGE { get; set; }
        public EGT EGT { get; set; }
        public ELA ELA { get; set; }
        public NRG NRG { get; set; }
        public GNT GNT { get; set; }
        public GRIN GRIN { get; set; }
        public GXC GXC { get; set; }
        public HOT HOT { get; set; }
        public HT HT { get; set; }
        public KMD KMD { get; set; }
        public KCS KCS { get; set; }
        public LAMB LAMB { get; set; }
        public LEO LEO { get; set; }
        public LSK LSK { get; set; }
        public MAID MAID { get; set; }
        public MKR MKR { get; set; }
        public ETP ETP { get; set; }
        public MONA MONA { get; set; }
        public NANO NANO { get; set; }
        public NAS NAS { get; set; }
        public XEM XEM { get; set; }
        public NEX NEX { get; set; }
        public NEXO NEXO { get; set; }
        public NULS NULS { get; set; }
        public OKB OKB { get; set; }
        public ONT ONT { get; set; }
        public PAX PAX { get; set; }
        public NPXS NPXS { get; set; }
        public QTUM QTUM { get; set; }
        public QNT QNT { get; set; }
        public QKC QKC { get; set; }
        public RVN RVN { get; set; }
        public REN REN { get; set; }
        public RR RR { get; set; }
        public SC SC { get; set; }
        public SOLVE SOLVE { get; set; }
        public SNT SNT { get; set; }
        public STEEM STEEM { get; set; }
        public XTZ XTZ { get; set; }
        public THETA THETA { get; set; }
        public TUSD TUSD { get; set; }
        public USDC USDC { get; set; }
        public VSYS VSYS { get; set; }
        public XVG XVG { get; set; }
        public MCO MCO { get; set; }
        public XAUT XAUT { get; set; }
        public NMR NMR { get; set; }
        public CKB CKB { get; set; }
        public DIVI DIVI { get; set; }
        public DX DX { get; set; }
        public CEL CEL { get; set; }
        public STX STX { get; set; }
        public BUSD BUSD { get; set; }
        public HBAR HBAR { get; set; }
        public ETN ETN { get; set; }
        public HUSD HUSD { get; set; }
        public GT GT { get; set; }
        public HYN HYN { get; set; }
        public UBT UBT { get; set; }
        public LUNA LUNA { get; set; }
        public MATIC MATIC { get; set; }
        public HIVE HIVE { get; set; }
        public FTT FTT { get; set; }
        public KNC KNC { get; set; }
        public UMA UMA { get; set; }
        public CHZ CHZ { get; set; }
        public CETH CETH { get; set; }
        public LRC LRC { get; set; }
        public HAV HAV { get; set; }
        public DOT DOT { get; set; }
        public CELO CELO { get; set; }
        public YFI YFI { get; set; }
        public CHSB CHSB { get; set; }
        public AVAX AVAX { get; set; }
        public UNI UNI { get; set; }
        public NXM NXM { get; set; }
        public AMP AMP { get; set; }
        public CRV CRV { get; set; }
        public AAVE AAVE { get; set; }
        public CDAI CDAI { get; set; }
        public CAKE CAKE { get; set; }
        public _1INCH _1INCH { get; set; }
        public RENBTC RENBTC { get; set; }
        public NEAR NEAR { get; set; }
        public RSR RSR { get; set; }
        public ALPHA ALPHA { get; set; }
        public SOL SOL { get; set; }
        public COMP COMP { get; set; }
        public WBTC WBTC { get; set; }
        public KSM KSM { get; set; }
        public FIL FIL { get; set; }
        public BAL BAL { get; set; }
        public EGLD EGLD { get; set; }
        public RUNE RUNE { get; set; }
        public CUSDC CUSDC { get; set; }
        public SUSHI SUSHI { get; set; }
        public GRT GRT { get; set; }
        public OCEAN OCEAN { get; set; }
        public ETHOS ETHOS { get; set; }
        public FTM FTM { get; set; }
        public AMPL AMPL { get; set; }
        public HBTC HBTC { get; set; }
        public ANKR ANKR { get; set; }
        public AR AR { get; set; }
        public BAKE BAKE { get; set; }
        public BNT BNT { get; set; }
        public CUSDT CUSDT { get; set; }
        public FEI FEI { get; set; }
        public ONE ONE { get; set; }
        public HNT HNT { get; set; }
        public ICP ICP { get; set; }
        public LUSD LUSD { get; set; }
        public LPT LPT { get; set; }
        public MDX MDX { get; set; }
        public MINA MINA { get; set; }
        public ARRR ARRR { get; set; }
        public SAFEMOON SAFEMOON { get; set; }
        public SHIB SHIB { get; set; }
        public STETH STETH { get; set; }
        public TEL TEL { get; set; }
        public UST UST { get; set; }
        public TFUEL TFUEL { get; set; }
        public XVS XVS { get; set; }
        public WRX WRX { get; set; }
        public XSUSHI XSUSHI { get; set; }
        public KLAY KLAY { get; set; }
        public XEC XEC { get; set; }
        public OSMO OSMO { get; set; }
        public OMI OMI { get; set; }
        public FLOW FLOW { get; set; }
        public CLOUT CLOUT { get; set; }
        public BCHA BCHA { get; set; }
        public OHM OHM { get; set; }
        public AXS AXS { get; set; }
        public COTI COTI { get; set; }
        public CEEK CEEK { get; set; }
    }
}